server:
  port: 8081

mybatis:
  type-aliases-package: com.ethan.cloud.entities       # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml  # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

spring:
  application:
    name: service-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver         # mysql驱动包
    url: jdbc:mysql://198.13.54.200/cloud01?useSSL=false                # 数据库名称
    username: root
    password: 'hello@123'
    dbcp2:
      min-idle: 5                                      # 数据库连接池的最小维持连接数
      initial-size: 5                                  # 初始化连接数
      max-total: 5                                     # 最大连接数
      max-wait-millis: 200                             # 等待连接获取的最大超时时间
